name: pipeline

on: push

jobs:
  pipeline:
    name: Pipeline
    runs-on: python:3.9
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install requirements
        run : |
          pip install -r requirements.txt

      - name: flake8
        run: |
          flake8 .

      - name: mypy
        run: |
          mypy .

      - name: pytest
        run: |
          pytest
